---

# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler/blob/master/README.md

on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      os:
        description: The operating system to run the workflow on
        required: true
        type: string
        default: ubuntu-latest
    secrets:
      token:
        description: The GitHub token to use when applying labels
        required: true

name: üè∑Ô∏è Add labels

jobs:
  label:
    runs-on: ${{ inputs.os }}
    steps:
      - name: üè∑Ô∏è Apply labels
        uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.token }}"

...
